FLA-1165 getting migrated code running
bcgov/jag-ai-reviewer pull request #20
Opened 2021-05-12 20:42 UTC by KDNeufeld

# Description

This PR includes the following proposed change(s):

- {List all the changes, if possible add the jira ticket #}

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2021-05-12 21:00 UTC, TayGov commented on docker-compose.yml
> +      - "8090:8090"
```suggestion
      - "8090:8080"
```

2021-05-12 21:00 UTC, TayGov commented on src/backend/efiling-reviewer-api/src/main/resources/application.yml
> +  port: ${SERVER_PORT:8090}
```suggestion
  port: ${SERVER_PORT:8080}
```

2021-05-12 21:01 UTC, TayGov requested changes
My only suggestion is the port remain default to 8080 as this has implications in openshift. Otherwise this is awesome!

2021-05-12 21:43 UTC, KDNeufeld commented on docker-compose.yml
> +      - "8090:8090"
sounds good

2021-05-13 14:13 UTC, TayGov approved these changes

2021-05-13 14:13 UTC, merged